using System;
using System.Security.Cryptography;
using System.Text;


namespace ClassLibrary
{
    public class HashGenerator
    {
        /// <summary>
        /// Generate the hash to be returned to the database
        /// </summary>
        /// <param name="input">password input</param>
        /// <param name="salt">salt generated by SaltGeneratorClass</param>
        /// <returns></returns>
        public static string GenerateHashSHA256Hash(string input, string salt)
        {
            byte[] hash = Encoding.UTF8.GetBytes(salt + input);
            SHA256Managed sHA256Managed = new SHA256Managed();
            sHA256Managed.ComputeHash(hash);
            return Convert.ToBase64String(hash);
        }
    }
}
